//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Personal_Info_CRUD.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Info
    {
        public int SL { get; set; }
        public string Name { get; set; }
        public int Age { get; set; }
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:dd-MM-yy}")]
        public System.DateTime DOB { get; set; }
        public string Address { get; set; }
        public string Status { get; set; }
        public System.DateTime DataInsertTime { get; set; }
    }
}
